[assembly: System.Reflection.AssemblyTitle("Ldg")]
[assembly: System.Reflection.AssemblyDescription("Ldg")]
[assembly: System.Reflection.AssemblyConfiguration("")]
[assembly: System.Reflection.AssemblyCompany("Gruppo Ragni")]
[assembly: System.Reflection.AssemblyProduct("Ldg")]
[assembly: System.Reflection.AssemblyCopyright("Copyright 2011 Gruppo Ragni. All rights reserved.")]
[assembly: System.Reflection.AssemblyTrademark("Microligne s.r.l")]
[assembly: System.Reflection.AssemblyCulture("")]
[assembly: System.Reflection.AssemblyVersion("0.0.1")]
[assembly: System.Reflection.AssemblyDelaySign(false)]
[assembly: System.Reflection.AssemblyKeyFile("")]
[assembly: System.Reflection.AssemblyKeyName("")]